/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lingo_ffmpeg_lingoplayer_FFMpegLib */
#include <string.h>
#include <unistd.h>

#ifndef _Included_com_lingo_ffmpeg_lingoplayer_FFMpegLib
#define _Included_com_lingo_ffmpeg_lingoplayer_FFMpegLib

extern JNIEnv* g_env;
extern jobject g_job;
extern jmethodID g_method;
extern JavaVM *g_jvm;

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lingo_ffmpeg_lingoplayer_FFMpegLib
 * Method:    initplayer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lingo_ffmpeg_lingoplayer_FFMpegLib_initplayer
  (JNIEnv *env, jobject job);

/*
 * Class:     com_lingo_ffmpeg_lingoplayer_FFMpegLib
 * Method:    player
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lingo_ffmpeg_lingoplayer_FFMpegLib_player
  (JNIEnv *env, jobject job, jstring jstr);

/*
 * Class:     com_lingo_ffmpeg_lingoplayer_FFMpegLib
 * Method:    pause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lingo_ffmpeg_lingoplayer_FFMpegLib_pause
  (JNIEnv *env, jobject job);

/*
 * Class:     com_lingo_ffmpeg_lingoplayer_FFMpegLib
 * Method:    resume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lingo_ffmpeg_lingoplayer_FFMpegLib_resume
  (JNIEnv *env, jobject job);

/*
 * Class:     com_lingo_ffmpeg_lingoplayer_FFMpegLib
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lingo_ffmpeg_lingoplayer_FFMpegLib_stop
  (JNIEnv *env, jobject job);

  /*
 * Class:     com_lingo_ffmpeg_lingoplayer_FFMpegLib
 * Method:    release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lingo_ffmpeg_lingoplayer_FFMpegLib_release
  (JNIEnv *env, jobject job);

/*
 * Class:     com_lingo_ffmpeg_lingoplayer_FFMpegLib
 * Method:    next
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lingo_ffmpeg_lingoplayer_FFMpegLib_next
  (JNIEnv *env, jobject job, jstring jstr);

#ifdef __cplusplus
}
#endif
#endif
